#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackHome.Resource", IsApplication=true)]

namespace HackHome
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AccesoServicio.Resource.Animation.slide_in_right = global::HackHome.Resource.Animation.slide_in_right;
			global::AccesoServicio.Resource.Animation.slide_out_left = global::HackHome.Resource.Animation.slide_out_left;
			global::AccesoServicio.Resource.Drawable.ic_arrow_back = global::HackHome.Resource.Drawable.ic_arrow_back;
			global::AccesoServicio.Resource.Id.webview = global::HackHome.Resource.Id.webview;
			global::AccesoServicio.Resource.Layout.activity_webview = global::HackHome.Resource.Layout.activity_webview;
			global::AccesoServicio.Resource.String.ApplicationName = global::HackHome.Resource.String.ApplicationName;
			global::AccesoServicio.Resource.String.Hello = global::HackHome.Resource.String.Hello;
			global::AccesoServicio.Resource.String.title_activity_webview = global::HackHome.Resource.String.title_activity_webview;
			global::CapaComponentes.Resource.String.ApplicationName = global::HackHome.Resource.String.ApplicationName;
			global::CapaComponentes.Resource.String.Hello = global::HackHome.Resource.String.Hello;
			global::CapaEntidades.Resource.String.ApplicationName = global::HackHome.Resource.String.ApplicationName;
			global::CapaEntidades.Resource.String.Hello = global::HackHome.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int buttonValidate = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int editTextEmail = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int editTextPassword = 2131099662;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout3 = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int listViewEvidences = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textView2 = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int textView4 = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int textViewNombre = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int textViewNombreLab = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int textViewStatus = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int textViewTitulo = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int webView = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailEvidence = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Evidences = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layoutEvidence = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int Description = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Evidence = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Validate = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
